#include "pch.h"
#include <bakkesmod/wrappers/Engine/EngineTAWrapper.h>
#include <bakkesmod/wrappers/Engine/UnrealStringWrapper.h>
#include <bakkesmod/wrappers/GameEvent/ReplayDirectorWrapper.h>
#include <bakkesmod/wrappers/GameEvent/ReplaySoccarWrapper.h>
#include <bakkesmod/wrappers/GameObject/BaseCameraWrapper.h>
#include <bakkesmod/wrappers/GameObject/CarComponent/AirControlComponentWrapper.h>
#include <bakkesmod/wrappers/GameObject/CarComponent/BoostWrapper.h>
#include <bakkesmod/wrappers/GameObject/CarComponent/FlipCarComponentWrapper.h>
#include <bakkesmod/wrappers/GameObject/CarComponent/PrimitiveComponentWrapper.h>
#include <bakkesmod/wrappers/StructArrayWrapper.h>
#include <bakkesmod/wrappers/arraywrapper.h>
#include <iterator>
#include <memory>
#include <sstream> // __str__
#include <string>


void bind_unknown_unknown_10(py::module &M)
{
	{ // TeamGameEventWrapper file: line:11
		pybind11::class_<TeamGameEventWrapper, std::shared_ptr<TeamGameEventWrapper>, GameEventWrapper> cl(M, "TeamGameEventWrapper");
		pybind11::handle cl_type = cl;

		cl.def( pybind11::init<unsigned long>(), pybind11::arg("mem") );

		cl.def( pybind11::init( [](TeamGameEventWrapper const &o){ return new TeamGameEventWrapper(o); } ) );
		cl.def("assign", (class TeamGameEventWrapper & (TeamGameEventWrapper::*)(class TeamGameEventWrapper)) &TeamGameEventWrapper::operator=, "C++: TeamGameEventWrapper::operator=(class TeamGameEventWrapper) --> class TeamGameEventWrapper &", pybind11::return_value_policy::automatic, "rhs"_a);
		cl.def("GetTeamArchetypes", (class ArrayWrapper<class TeamWrapper> (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetTeamArchetypes, "C++: TeamGameEventWrapper::GetTeamArchetypes() --> class ArrayWrapper<class TeamWrapper>");
		cl.def("GetTeams", (class ArrayWrapper<class TeamWrapper> (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetTeams, "C++: TeamGameEventWrapper::GetTeams() --> class ArrayWrapper<class TeamWrapper>");
		cl.def("GetMaxTeamSize", (int (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetMaxTeamSize, "C++: TeamGameEventWrapper::GetMaxTeamSize() --> int");
		cl.def("SetMaxTeamSize", (void (TeamGameEventWrapper::*)(int)) &TeamGameEventWrapper::SetMaxTeamSize, "C++: TeamGameEventWrapper::SetMaxTeamSize(int) --> void", "newMaxTeamSize"_a);
		cl.def("GetNumBots", (int (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetNumBots, "C++: TeamGameEventWrapper::GetNumBots() --> int");
		cl.def("SetNumBots", (void (TeamGameEventWrapper::*)(int)) &TeamGameEventWrapper::SetNumBots, "C++: TeamGameEventWrapper::SetNumBots(int) --> void", "newNumBots"_a);
		cl.def("GetbMuteOppositeTeams", (unsigned long (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetbMuteOppositeTeams, "C++: TeamGameEventWrapper::GetbMuteOppositeTeams() --> unsigned long");
		cl.def("SetbMuteOppositeTeams", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetbMuteOppositeTeams, "C++: TeamGameEventWrapper::SetbMuteOppositeTeams(unsigned long) --> void", "newbMuteOppositeTeams"_a);
		cl.def("GetbDisableMutingOtherTeam", (unsigned long (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetbDisableMutingOtherTeam, "C++: TeamGameEventWrapper::GetbDisableMutingOtherTeam() --> unsigned long");
		cl.def("SetbDisableMutingOtherTeam", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetbDisableMutingOtherTeam, "C++: TeamGameEventWrapper::SetbDisableMutingOtherTeam(unsigned long) --> void", "newbDisableMutingOtherTeam"_a);
		cl.def("GetbForfeit", (unsigned long (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetbForfeit, "C++: TeamGameEventWrapper::GetbForfeit() --> unsigned long");
		cl.def("SetbForfeit", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetbForfeit, "C++: TeamGameEventWrapper::SetbForfeit(unsigned long) --> void", "newbForfeit"_a);
		cl.def("GetbUnfairTeams", (unsigned long (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetbUnfairTeams, "C++: TeamGameEventWrapper::GetbUnfairTeams() --> unsigned long");
		cl.def("SetbUnfairTeams", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetbUnfairTeams, "C++: TeamGameEventWrapper::SetbUnfairTeams(unsigned long) --> void", "newbUnfairTeams"_a);
		cl.def("GetbAlwaysAutoSelectTeam", (unsigned long (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::GetbAlwaysAutoSelectTeam, "C++: TeamGameEventWrapper::GetbAlwaysAutoSelectTeam() --> unsigned long");
		cl.def("SetbAlwaysAutoSelectTeam", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetbAlwaysAutoSelectTeam, "C++: TeamGameEventWrapper::SetbAlwaysAutoSelectTeam(unsigned long) --> void", "newbAlwaysAutoSelectTeam"_a);
		cl.def("StartRematchVote", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::StartRematchVote, "C++: TeamGameEventWrapper::StartRematchVote() --> void");
		cl.def("CheckRematchVote", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::CheckRematchVote, "C++: TeamGameEventWrapper::CheckRematchVote() --> void");
		cl.def("__GameEvent_Team_TA__AllTeamsHaveHumans", (bool (TeamGameEventWrapper::*)(class TeamWrapper)) &TeamGameEventWrapper::__GameEvent_Team_TA__AllTeamsHaveHumans, "C++: TeamGameEventWrapper::__GameEvent_Team_TA__AllTeamsHaveHumans(class TeamWrapper) --> bool", "Team"_a);
		cl.def("UpdatePlayerShortcuts", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::UpdatePlayerShortcuts, "C++: TeamGameEventWrapper::UpdatePlayerShortcuts() --> void");
		cl.def("ClearTemporarySpawnSpots", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::ClearTemporarySpawnSpots, "C++: TeamGameEventWrapper::ClearTemporarySpawnSpots() --> void");
		cl.def("ChooseTeam", (bool (TeamGameEventWrapper::*)(int, class PlayerControllerWrapper)) &TeamGameEventWrapper::ChooseTeam, "C++: TeamGameEventWrapper::ChooseTeam(int, class PlayerControllerWrapper) --> bool", "TeamIndex"_a, "Player"_a);
		cl.def("CanChangeTeam", (bool (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::CanChangeTeam, "C++: TeamGameEventWrapper::CanChangeTeam() --> bool");
		cl.def("OnPenaltyChanged", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::OnPenaltyChanged, "C++: TeamGameEventWrapper::OnPenaltyChanged() --> void");
		cl.def("OnTeamForfeited", (void (TeamGameEventWrapper::*)(class TeamWrapper)) &TeamGameEventWrapper::OnTeamForfeited, "C++: TeamGameEventWrapper::OnTeamForfeited(class TeamWrapper) --> void", "Team"_a);
		cl.def("HandleTeamForfeit", (void (TeamGameEventWrapper::*)(class TeamWrapper)) &TeamGameEventWrapper::HandleTeamForfeit, "C++: TeamGameEventWrapper::HandleTeamForfeit(class TeamWrapper) --> void", "Team"_a);
		cl.def("MuteOppositeTeams2", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::MuteOppositeTeams2, "C++: TeamGameEventWrapper::MuteOppositeTeams2(unsigned long) --> void", "bMute"_a);
		cl.def("UpdateBotCount", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::UpdateBotCount, "C++: TeamGameEventWrapper::UpdateBotCount() --> void");
		cl.def("FindBotReplacement", (bool (TeamGameEventWrapper::*)(class PriWrapper)) &TeamGameEventWrapper::FindBotReplacement, "C++: TeamGameEventWrapper::FindBotReplacement(class PriWrapper) --> bool", "PRI"_a);
		cl.def("EndGame", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::EndGame, "C++: TeamGameEventWrapper::EndGame() --> void");
		cl.def("ForceNoContest", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::ForceNoContest, "C++: TeamGameEventWrapper::ForceNoContest() --> void");
		cl.def("AddTemporarySpawnSpot", (void (TeamGameEventWrapper::*)(class TeamWrapper, class CarWrapper)) &TeamGameEventWrapper::AddTemporarySpawnSpot, "C++: TeamGameEventWrapper::AddTemporarySpawnSpot(class TeamWrapper, class CarWrapper) --> void", "Team"_a, "Car"_a);
		cl.def("HandleSelectedLoadout", (void (TeamGameEventWrapper::*)(class PriWrapper)) &TeamGameEventWrapper::HandleSelectedLoadout, "C++: TeamGameEventWrapper::HandleSelectedLoadout(class PriWrapper) --> void", "PlayerPRI"_a);
		cl.def("DestroyTeams", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::DestroyTeams, "C++: TeamGameEventWrapper::DestroyTeams() --> void");
		cl.def("OnAllTeamsCreated", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::OnAllTeamsCreated, "C++: TeamGameEventWrapper::OnAllTeamsCreated() --> void");
		cl.def("AssignCustomTeamSettings", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::AssignCustomTeamSettings, "C++: TeamGameEventWrapper::AssignCustomTeamSettings() --> void");
		cl.def("OnMatchSettingsChanged", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::OnMatchSettingsChanged, "C++: TeamGameEventWrapper::OnMatchSettingsChanged() --> void");
		cl.def("AllTeamsHaveHumans2", (bool (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::AllTeamsHaveHumans2, "C++: TeamGameEventWrapper::AllTeamsHaveHumans2() --> bool");
		cl.def("AllTeamsCreated2", (bool (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::AllTeamsCreated2, "C++: TeamGameEventWrapper::AllTeamsCreated2() --> bool");
		cl.def("SetTeam", (void (TeamGameEventWrapper::*)(int, class TeamWrapper)) &TeamGameEventWrapper::SetTeam, "C++: TeamGameEventWrapper::SetTeam(int, class TeamWrapper) --> void", "TeamNum"_a, "NewTeam"_a);
		cl.def("CreateTeams", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::CreateTeams, "C++: TeamGameEventWrapper::CreateTeams() --> void");
		cl.def("PreloadBots", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::PreloadBots, "C++: TeamGameEventWrapper::PreloadBots() --> void");
		cl.def("OnInit", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::OnInit, "C++: TeamGameEventWrapper::OnInit() --> void");
		cl.def("SetMaxTeamSize2", (void (TeamGameEventWrapper::*)(int)) &TeamGameEventWrapper::SetMaxTeamSize2, "C++: TeamGameEventWrapper::SetMaxTeamSize2(int) --> void", "MaxSize"_a);
		cl.def("UpdateMaxTeamSize", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::UpdateMaxTeamSize, "C++: TeamGameEventWrapper::UpdateMaxTeamSize() --> void");
		cl.def("SetUnfairTeams", (void (TeamGameEventWrapper::*)(unsigned long)) &TeamGameEventWrapper::SetUnfairTeams, "C++: TeamGameEventWrapper::SetUnfairTeams(unsigned long) --> void", "bUnfair"_a);
		cl.def("InitBotSkill", (void (TeamGameEventWrapper::*)()) &TeamGameEventWrapper::InitBotSkill, "C++: TeamGameEventWrapper::InitBotSkill() --> void");
		cl.def("eventInitGame", (void (TeamGameEventWrapper::*)(std::string)) &TeamGameEventWrapper::eventInitGame, "C++: TeamGameEventWrapper::eventInitGame(std::string) --> void", "Options"_a);
	}
	{ // ServerWrapper file: line:15
		pybind11::class_<ServerWrapper, std::shared_ptr<ServerWrapper>, TeamGameEventWrapper> cl(M, "ServerWrapper");
		pybind11::handle cl_type = cl;

		cl.def( pybind11::init<unsigned long>(), pybind11::arg("mem") );

		cl.def( pybind11::init( [](ServerWrapper const &o){ return new ServerWrapper(o); } ) );
		cl.def("assign", (class ServerWrapper & (ServerWrapper::*)(class ServerWrapper)) &ServerWrapper::operator=, "C++: ServerWrapper::operator=(class ServerWrapper) --> class ServerWrapper &", pybind11::return_value_policy::automatic, "rhs"_a);
		cl.def("GetBall", (class BallWrapper (ServerWrapper::*)()) &ServerWrapper::GetBall, "C++: ServerWrapper::GetBall() --> class BallWrapper");
		cl.def("SpawnCar", (void (ServerWrapper::*)(int, std::string)) &ServerWrapper::SpawnCar, "C++: ServerWrapper::SpawnCar(int, std::string) --> void", "carBody"_a, "name"_a);
		cl.def("SpawnBot", (void (ServerWrapper::*)(int, std::string)) &ServerWrapper::SpawnBot, "C++: ServerWrapper::SpawnBot(int, std::string) --> void", "carBody"_a, "name"_a);
		cl.def("SpawnBall", (class BallWrapper (ServerWrapper::*)(const struct Vector, bool, bool)) &ServerWrapper::SpawnBall, "C++: ServerWrapper::SpawnBall(const struct Vector, bool, bool) --> class BallWrapper", "position"_a, "wake"_a, "spawnCannon"_a);
		cl.def("HasAuthority", (bool (ServerWrapper::*)()) &ServerWrapper::HasAuthority, "C++: ServerWrapper::HasAuthority() --> bool");
		cl.def("SetGameSpeed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetGameSpeed, "C++: ServerWrapper::SetGameSpeed(float) --> void", "GameSpeed"_a);
		cl.def("GetGameSpeed", (float (ServerWrapper::*)()) &ServerWrapper::GetGameSpeed, "C++: ServerWrapper::GetGameSpeed() --> float");
		cl.def("SetSecondsElapsed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetSecondsElapsed, "C++: ServerWrapper::SetSecondsElapsed(float) --> void", "SecondsElapsed"_a);
		cl.def("GetSecondsElapsed", (float (ServerWrapper::*)()) &ServerWrapper::GetSecondsElapsed, "C++: ServerWrapper::GetSecondsElapsed() --> float");
		cl.def("GetGameCar", (class CarWrapper (ServerWrapper::*)()) &ServerWrapper::GetGameCar, "C++: ServerWrapper::GetGameCar() --> class CarWrapper");
		cl.def("IsBallMovingTowardsGoal", (bool (ServerWrapper::*)(int, class BallWrapper)) &ServerWrapper::IsBallMovingTowardsGoal, "C++: ServerWrapper::IsBallMovingTowardsGoal(int, class BallWrapper) --> bool", "goalNo"_a, "bw"_a);
		cl.def("IsInGoal", (bool (ServerWrapper::*)(struct Vector)) &ServerWrapper::IsInGoal, "C++: ServerWrapper::IsInGoal(struct Vector) --> bool", "vec"_a);
		cl.def("DisableGoalReset", (void (ServerWrapper::*)()) &ServerWrapper::DisableGoalReset, "C++: ServerWrapper::DisableGoalReset() --> void");
		cl.def("EnableGoalReset", (void (ServerWrapper::*)()) &ServerWrapper::EnableGoalReset, "C++: ServerWrapper::EnableGoalReset() --> void");
		cl.def("GenerateShot", (struct Vector (ServerWrapper::*)(struct Vector, struct Vector, float)) &ServerWrapper::GenerateShot, "C++: ServerWrapper::GenerateShot(struct Vector, struct Vector, float) --> struct Vector", "startPos"_a, "destination"_a, "speed"_a);
		cl.def("GenerateGoalAimLocation", (struct Vector (ServerWrapper::*)(int, struct Vector)) &ServerWrapper::GenerateGoalAimLocation, "C++: ServerWrapper::GenerateGoalAimLocation(int, struct Vector) --> struct Vector", "goalNumber"_a, "currentBallLocation"_a);
		cl.def("GetGoalExtent", [](ServerWrapper &o) -> Vector { return o.GetGoalExtent(); }, "");
		cl.def("GetGoalExtent", (struct Vector (ServerWrapper::*)(int)) &ServerWrapper::GetGoalExtent, "C++: ServerWrapper::GetGoalExtent(int) --> struct Vector", "goalNumber"_a = 0);
		cl.def("GetGoalLocation", [](ServerWrapper &o) -> Vector { return o.GetGoalLocation(); }, "");
		cl.def("GetGoalLocation", (struct Vector (ServerWrapper::*)(int)) &ServerWrapper::GetGoalLocation, "C++: ServerWrapper::GetGoalLocation(int) --> struct Vector", "goalNumber"_a = 0);
		cl.def("GetTestCarArchetype", (class CarWrapper (ServerWrapper::*)()) &ServerWrapper::GetTestCarArchetype, "C++: ServerWrapper::GetTestCarArchetype() --> class CarWrapper");
		cl.def("SetTestCarArchetype", (void (ServerWrapper::*)(class CarWrapper)) &ServerWrapper::SetTestCarArchetype, "C++: ServerWrapper::SetTestCarArchetype(class CarWrapper) --> void", "newTestCarArchetype"_a);
		cl.def("GetBallArchetype", (class BallWrapper (ServerWrapper::*)()) &ServerWrapper::GetBallArchetype, "C++: ServerWrapper::GetBallArchetype() --> class BallWrapper");
		cl.def("SetBallArchetype", (void (ServerWrapper::*)(class BallWrapper)) &ServerWrapper::SetBallArchetype, "C++: ServerWrapper::SetBallArchetype(class BallWrapper) --> void", "newBallArchetype"_a);
		cl.def("GetBallSpawnPoint", (class ActorWrapper (ServerWrapper::*)()) &ServerWrapper::GetBallSpawnPoint, "C++: ServerWrapper::GetBallSpawnPoint() --> class ActorWrapper");
		cl.def("SetBallSpawnPoint", (void (ServerWrapper::*)(class ActorWrapper)) &ServerWrapper::SetBallSpawnPoint, "C++: ServerWrapper::SetBallSpawnPoint(class ActorWrapper) --> void", "newBallSpawnPoint"_a);
		cl.def("GetSeriesLength", (int (ServerWrapper::*)()) &ServerWrapper::GetSeriesLength, "C++: ServerWrapper::GetSeriesLength() --> int");
		cl.def("SetSeriesLength", (void (ServerWrapper::*)(int)) &ServerWrapper::SetSeriesLength, "C++: ServerWrapper::SetSeriesLength(int) --> void", "newSeriesLength"_a);
		cl.def("GetGameTime", (int (ServerWrapper::*)()) &ServerWrapper::GetGameTime, "C++: ServerWrapper::GetGameTime() --> int");
		cl.def("SetGameTime", (void (ServerWrapper::*)(int)) &ServerWrapper::SetGameTime, "C++: ServerWrapper::SetGameTime(int) --> void", "newGameTime"_a);
		cl.def("GetWarmupTime", (int (ServerWrapper::*)()) &ServerWrapper::GetWarmupTime, "C++: ServerWrapper::GetWarmupTime() --> int");
		cl.def("SetWarmupTime", (void (ServerWrapper::*)(int)) &ServerWrapper::SetWarmupTime, "C++: ServerWrapper::SetWarmupTime(int) --> void", "newWarmupTime"_a);
		cl.def("GetMaxScore", (int (ServerWrapper::*)()) &ServerWrapper::GetMaxScore, "C++: ServerWrapper::GetMaxScore() --> int");
		cl.def("SetMaxScore", (void (ServerWrapper::*)(int)) &ServerWrapper::SetMaxScore, "C++: ServerWrapper::SetMaxScore(int) --> void", "newMaxScore"_a);
		cl.def("GetAutoBalanceDifference", (int (ServerWrapper::*)()) &ServerWrapper::GetAutoBalanceDifference, "C++: ServerWrapper::GetAutoBalanceDifference() --> int");
		cl.def("SetAutoBalanceDifference", (void (ServerWrapper::*)(int)) &ServerWrapper::SetAutoBalanceDifference, "C++: ServerWrapper::SetAutoBalanceDifference(int) --> void", "newAutoBalanceDifference"_a);
		cl.def("GetScoreSlomoTime", (float (ServerWrapper::*)()) &ServerWrapper::GetScoreSlomoTime, "C++: ServerWrapper::GetScoreSlomoTime() --> float");
		cl.def("SetScoreSlomoTime", (void (ServerWrapper::*)(float)) &ServerWrapper::SetScoreSlomoTime, "C++: ServerWrapper::SetScoreSlomoTime(float) --> void", "newScoreSlomoTime"_a);
		cl.def("GetGameTimeRemaining", (float (ServerWrapper::*)()) &ServerWrapper::GetGameTimeRemaining, "C++: ServerWrapper::GetGameTimeRemaining() --> float");
		cl.def("SetGameTimeRemaining", (void (ServerWrapper::*)(float)) &ServerWrapper::SetGameTimeRemaining, "C++: ServerWrapper::SetGameTimeRemaining(float) --> void", "newGameTimeRemaining"_a);
		cl.def("GetSecondsRemaining", (int (ServerWrapper::*)()) &ServerWrapper::GetSecondsRemaining, "C++: ServerWrapper::GetSecondsRemaining() --> int");
		cl.def("SetSecondsRemaining", (void (ServerWrapper::*)(int)) &ServerWrapper::SetSecondsRemaining, "C++: ServerWrapper::SetSecondsRemaining(int) --> void", "newSecondsRemaining"_a);
		cl.def("GetWaitTimeRemaining", (int (ServerWrapper::*)()) &ServerWrapper::GetWaitTimeRemaining, "C++: ServerWrapper::GetWaitTimeRemaining() --> int");
		cl.def("SetWaitTimeRemaining", (void (ServerWrapper::*)(int)) &ServerWrapper::SetWaitTimeRemaining, "C++: ServerWrapper::SetWaitTimeRemaining(int) --> void", "newWaitTimeRemaining"_a);
		cl.def("GetTotalGameTimePlayed", (float (ServerWrapper::*)()) &ServerWrapper::GetTotalGameTimePlayed, "C++: ServerWrapper::GetTotalGameTimePlayed() --> float");
		cl.def("SetTotalGameTimePlayed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetTotalGameTimePlayed, "C++: ServerWrapper::SetTotalGameTimePlayed(float) --> void", "newTotalGameTimePlayed"_a);
		cl.def("GetOvertimeTimePlayed", (float (ServerWrapper::*)()) &ServerWrapper::GetOvertimeTimePlayed, "C++: ServerWrapper::GetOvertimeTimePlayed() --> float");
		cl.def("SetOvertimeTimePlayed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetOvertimeTimePlayed, "C++: ServerWrapper::SetOvertimeTimePlayed(float) --> void", "newOvertimeTimePlayed"_a);
		cl.def("GetbRoundActive", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbRoundActive, "C++: ServerWrapper::GetbRoundActive() --> unsigned long");
		cl.def("SetbRoundActive", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbRoundActive, "C++: ServerWrapper::SetbRoundActive(unsigned long) --> void", "newbRoundActive"_a);
		cl.def("GetbPlayReplays", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbPlayReplays, "C++: ServerWrapper::GetbPlayReplays() --> unsigned long");
		cl.def("SetbPlayReplays", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbPlayReplays, "C++: ServerWrapper::SetbPlayReplays(unsigned long) --> void", "newbPlayReplays"_a);
		cl.def("GetbBallHasBeenHit", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbBallHasBeenHit, "C++: ServerWrapper::GetbBallHasBeenHit() --> unsigned long");
		cl.def("SetbBallHasBeenHit", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbBallHasBeenHit, "C++: ServerWrapper::SetbBallHasBeenHit(unsigned long) --> void", "newbBallHasBeenHit"_a);
		cl.def("GetbOverTime", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbOverTime, "C++: ServerWrapper::GetbOverTime() --> unsigned long");
		cl.def("SetbOverTime", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbOverTime, "C++: ServerWrapper::SetbOverTime(unsigned long) --> void", "newbOverTime"_a);
		cl.def("GetbUnlimitedTime", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbUnlimitedTime, "C++: ServerWrapper::GetbUnlimitedTime() --> unsigned long");
		cl.def("SetbUnlimitedTime", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbUnlimitedTime, "C++: ServerWrapper::SetbUnlimitedTime(unsigned long) --> void", "newbUnlimitedTime"_a);
		cl.def("GetbNoContest", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbNoContest, "C++: ServerWrapper::GetbNoContest() --> unsigned long");
		cl.def("SetbNoContest", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbNoContest, "C++: ServerWrapper::SetbNoContest(unsigned long) --> void", "newbNoContest"_a);
		cl.def("GetbDisableGoalDelay", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbDisableGoalDelay, "C++: ServerWrapper::GetbDisableGoalDelay() --> unsigned long");
		cl.def("SetbDisableGoalDelay", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbDisableGoalDelay, "C++: ServerWrapper::SetbDisableGoalDelay(unsigned long) --> void", "newbDisableGoalDelay"_a);
		cl.def("GetbShowNoScorerGoalMessage", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbShowNoScorerGoalMessage, "C++: ServerWrapper::GetbShowNoScorerGoalMessage() --> unsigned long");
		cl.def("SetbShowNoScorerGoalMessage", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbShowNoScorerGoalMessage, "C++: ServerWrapper::SetbShowNoScorerGoalMessage(unsigned long) --> void", "newbShowNoScorerGoalMessage"_a);
		cl.def("GetbMatchEnded", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbMatchEnded, "C++: ServerWrapper::GetbMatchEnded() --> unsigned long");
		cl.def("SetbMatchEnded", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbMatchEnded, "C++: ServerWrapper::SetbMatchEnded(unsigned long) --> void", "newbMatchEnded"_a);
		cl.def("GetbShowIntroScene", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbShowIntroScene, "C++: ServerWrapper::GetbShowIntroScene() --> unsigned long");
		cl.def("SetbShowIntroScene", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbShowIntroScene, "C++: ServerWrapper::SetbShowIntroScene(unsigned long) --> void", "newbShowIntroScene"_a);
		cl.def("GetbClubMatch", (unsigned long (ServerWrapper::*)()) &ServerWrapper::GetbClubMatch, "C++: ServerWrapper::GetbClubMatch() --> unsigned long");
		cl.def("SetbClubMatch", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetbClubMatch, "C++: ServerWrapper::SetbClubMatch(unsigned long) --> void", "newbClubMatch"_a);
		cl.def("GetNextSpawnIndex", (int (ServerWrapper::*)()) &ServerWrapper::GetNextSpawnIndex, "C++: ServerWrapper::GetNextSpawnIndex() --> int");
		cl.def("SetNextSpawnIndex", (void (ServerWrapper::*)(int)) &ServerWrapper::SetNextSpawnIndex, "C++: ServerWrapper::SetNextSpawnIndex(int) --> void", "newNextSpawnIndex"_a);
		cl.def("GetReplayDirectorArchetype", (class ReplayDirectorWrapper (ServerWrapper::*)()) &ServerWrapper::GetReplayDirectorArchetype, "C++: ServerWrapper::GetReplayDirectorArchetype() --> class ReplayDirectorWrapper");
		cl.def("SetReplayDirectorArchetype", (void (ServerWrapper::*)(class ReplayDirectorWrapper)) &ServerWrapper::SetReplayDirectorArchetype, "C++: ServerWrapper::SetReplayDirectorArchetype(class ReplayDirectorWrapper) --> void", "newReplayDirectorArchetype"_a);
		cl.def("GetReplayDirector", (class ReplayDirectorWrapper (ServerWrapper::*)()) &ServerWrapper::GetReplayDirector, "C++: ServerWrapper::GetReplayDirector() --> class ReplayDirectorWrapper");
		cl.def("SetReplayDirector", (void (ServerWrapper::*)(class ReplayDirectorWrapper)) &ServerWrapper::SetReplayDirector, "C++: ServerWrapper::SetReplayDirector(class ReplayDirectorWrapper) --> void", "newReplayDirector"_a);
		cl.def("GetGameBalls", (class ArrayWrapper<class BallWrapper> (ServerWrapper::*)()) &ServerWrapper::GetGameBalls, "C++: ServerWrapper::GetGameBalls() --> class ArrayWrapper<class BallWrapper>");
		cl.def("GetTotalGameBalls", (int (ServerWrapper::*)()) &ServerWrapper::GetTotalGameBalls, "C++: ServerWrapper::GetTotalGameBalls() --> int");
		cl.def("SetTotalGameBalls", (void (ServerWrapper::*)(int)) &ServerWrapper::SetTotalGameBalls, "C++: ServerWrapper::SetTotalGameBalls(int) --> void", "newTotalGameBalls"_a);
		cl.def("GetPostGoalTime", (float (ServerWrapper::*)()) &ServerWrapper::GetPostGoalTime, "C++: ServerWrapper::GetPostGoalTime() --> float");
		cl.def("SetPostGoalTime", (void (ServerWrapper::*)(float)) &ServerWrapper::SetPostGoalTime, "C++: ServerWrapper::SetPostGoalTime(float) --> void", "newPostGoalTime"_a);
		cl.def("GetGoals", (class ArrayWrapper<class GoalWrapper> (ServerWrapper::*)()) &ServerWrapper::GetGoals, "C++: ServerWrapper::GetGoals() --> class ArrayWrapper<class GoalWrapper>");
		cl.def("GetSecondsRemainingCountdown", (int (ServerWrapper::*)()) &ServerWrapper::GetSecondsRemainingCountdown, "C++: ServerWrapper::GetSecondsRemainingCountdown() --> int");
		cl.def("SetSecondsRemainingCountdown", (void (ServerWrapper::*)(int)) &ServerWrapper::SetSecondsRemainingCountdown, "C++: ServerWrapper::SetSecondsRemainingCountdown(int) --> void", "newSecondsRemainingCountdown"_a);
		cl.def("GetFieldCenter", (struct Vector (ServerWrapper::*)()) &ServerWrapper::GetFieldCenter, "C++: ServerWrapper::GetFieldCenter() --> struct Vector");
		cl.def("SetFieldCenter", (void (ServerWrapper::*)(struct Vector)) &ServerWrapper::SetFieldCenter, "C++: ServerWrapper::SetFieldCenter(struct Vector) --> void", "newFieldCenter"_a);
		cl.def("GetGameWinner", (class TeamWrapper (ServerWrapper::*)()) &ServerWrapper::GetGameWinner, "C++: ServerWrapper::GetGameWinner() --> class TeamWrapper");
		cl.def("SetGameWinner", (void (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::SetGameWinner, "C++: ServerWrapper::SetGameWinner(class TeamWrapper) --> void", "newGameWinner"_a);
		cl.def("GetMatchWinner", (class TeamWrapper (ServerWrapper::*)()) &ServerWrapper::GetMatchWinner, "C++: ServerWrapper::GetMatchWinner() --> class TeamWrapper");
		cl.def("SetMatchWinner", (void (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::SetMatchWinner, "C++: ServerWrapper::SetMatchWinner(class TeamWrapper) --> void", "newMatchWinner"_a);
		cl.def("GetMVP", (class PriWrapper (ServerWrapper::*)()) &ServerWrapper::GetMVP, "C++: ServerWrapper::GetMVP() --> class PriWrapper");
		cl.def("SetMVP", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::SetMVP, "C++: ServerWrapper::SetMVP(class PriWrapper) --> void", "newMVP"_a);
		cl.def("GetFastestGoalPlayer", (class PriWrapper (ServerWrapper::*)()) &ServerWrapper::GetFastestGoalPlayer, "C++: ServerWrapper::GetFastestGoalPlayer() --> class PriWrapper");
		cl.def("SetFastestGoalPlayer", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::SetFastestGoalPlayer, "C++: ServerWrapper::SetFastestGoalPlayer(class PriWrapper) --> void", "newFastestGoalPlayer"_a);
		cl.def("GetSlowestGoalPlayer", (class PriWrapper (ServerWrapper::*)()) &ServerWrapper::GetSlowestGoalPlayer, "C++: ServerWrapper::GetSlowestGoalPlayer() --> class PriWrapper");
		cl.def("SetSlowestGoalPlayer", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::SetSlowestGoalPlayer, "C++: ServerWrapper::SetSlowestGoalPlayer(class PriWrapper) --> void", "newSlowestGoalPlayer"_a);
		cl.def("GetFurthestGoalPlayer", (class PriWrapper (ServerWrapper::*)()) &ServerWrapper::GetFurthestGoalPlayer, "C++: ServerWrapper::GetFurthestGoalPlayer() --> class PriWrapper");
		cl.def("SetFurthestGoalPlayer", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::SetFurthestGoalPlayer, "C++: ServerWrapper::SetFurthestGoalPlayer(class PriWrapper) --> void", "newFurthestGoalPlayer"_a);
		cl.def("GetFastestGoalSpeed", (float (ServerWrapper::*)()) &ServerWrapper::GetFastestGoalSpeed, "C++: ServerWrapper::GetFastestGoalSpeed() --> float");
		cl.def("SetFastestGoalSpeed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetFastestGoalSpeed, "C++: ServerWrapper::SetFastestGoalSpeed(float) --> void", "newFastestGoalSpeed"_a);
		cl.def("GetSlowestGoalSpeed", (float (ServerWrapper::*)()) &ServerWrapper::GetSlowestGoalSpeed, "C++: ServerWrapper::GetSlowestGoalSpeed() --> float");
		cl.def("SetSlowestGoalSpeed", (void (ServerWrapper::*)(float)) &ServerWrapper::SetSlowestGoalSpeed, "C++: ServerWrapper::SetSlowestGoalSpeed(float) --> void", "newSlowestGoalSpeed"_a);
		cl.def("GetFurthestGoal", (float (ServerWrapper::*)()) &ServerWrapper::GetFurthestGoal, "C++: ServerWrapper::GetFurthestGoal() --> float");
		cl.def("SetFurthestGoal", (void (ServerWrapper::*)(float)) &ServerWrapper::SetFurthestGoal, "C++: ServerWrapper::SetFurthestGoal(float) --> void", "newFurthestGoal"_a);
		cl.def("GetReplicatedScoredOnTeam", (unsigned char (ServerWrapper::*)()) &ServerWrapper::GetReplicatedScoredOnTeam, "C++: ServerWrapper::GetReplicatedScoredOnTeam() --> unsigned char");
		cl.def("SetReplicatedScoredOnTeam", (void (ServerWrapper::*)(unsigned char)) &ServerWrapper::SetReplicatedScoredOnTeam, "C++: ServerWrapper::SetReplicatedScoredOnTeam(unsigned char) --> void", "newReplicatedScoredOnTeam"_a);
		cl.def("GetReplicatedServerPerformanceState", (unsigned char (ServerWrapper::*)()) &ServerWrapper::GetReplicatedServerPerformanceState, "C++: ServerWrapper::GetReplicatedServerPerformanceState() --> unsigned char");
		cl.def("SetReplicatedServerPerformanceState", (void (ServerWrapper::*)(unsigned char)) &ServerWrapper::SetReplicatedServerPerformanceState, "C++: ServerWrapper::SetReplicatedServerPerformanceState(unsigned char) --> void", "newReplicatedServerPerformanceState"_a);
		cl.def("GetRoundNum", (int (ServerWrapper::*)()) &ServerWrapper::GetRoundNum, "C++: ServerWrapper::GetRoundNum() --> int");
		cl.def("SetRoundNum", (void (ServerWrapper::*)(int)) &ServerWrapper::SetRoundNum, "C++: ServerWrapper::SetRoundNum(int) --> void", "newRoundNum"_a);
		cl.def("GetAssistMaxTime", (float (ServerWrapper::*)()) &ServerWrapper::GetAssistMaxTime, "C++: ServerWrapper::GetAssistMaxTime() --> float");
		cl.def("SetAssistMaxTime", (void (ServerWrapper::*)(float)) &ServerWrapper::SetAssistMaxTime, "C++: ServerWrapper::SetAssistMaxTime(float) --> void", "newAssistMaxTime"_a);
		cl.def("GetBallHasBeenHitStartDelay", (float (ServerWrapper::*)()) &ServerWrapper::GetBallHasBeenHitStartDelay, "C++: ServerWrapper::GetBallHasBeenHitStartDelay() --> float");
		cl.def("SetBallHasBeenHitStartDelay", (void (ServerWrapper::*)(float)) &ServerWrapper::SetBallHasBeenHitStartDelay, "C++: ServerWrapper::SetBallHasBeenHitStartDelay(float) --> void", "newBallHasBeenHitStartDelay"_a);
		cl.def("GetPodiumDelay", (float (ServerWrapper::*)()) &ServerWrapper::GetPodiumDelay, "C++: ServerWrapper::GetPodiumDelay() --> float");
		cl.def("SetPodiumDelay", (void (ServerWrapper::*)(float)) &ServerWrapper::SetPodiumDelay, "C++: ServerWrapper::SetPodiumDelay(float) --> void", "newPodiumDelay"_a);
		cl.def("GetPodiumTime", (float (ServerWrapper::*)()) &ServerWrapper::GetPodiumTime, "C++: ServerWrapper::GetPodiumTime() --> float");
		cl.def("SetPodiumTime", (void (ServerWrapper::*)(float)) &ServerWrapper::SetPodiumTime, "C++: ServerWrapper::SetPodiumTime(float) --> void", "newPodiumTime"_a);
		cl.def("GetLobbyEndCountdown", (int (ServerWrapper::*)()) &ServerWrapper::GetLobbyEndCountdown, "C++: ServerWrapper::GetLobbyEndCountdown() --> int");
		cl.def("SetLobbyEndCountdown", (void (ServerWrapper::*)(int)) &ServerWrapper::SetLobbyEndCountdown, "C++: ServerWrapper::SetLobbyEndCountdown(int) --> void", "newLobbyEndCountdown"_a);
		cl.def("GetLobbyCountdown", (int (ServerWrapper::*)()) &ServerWrapper::GetLobbyCountdown, "C++: ServerWrapper::GetLobbyCountdown() --> int");
		cl.def("SetLobbyCountdown", (void (ServerWrapper::*)(int)) &ServerWrapper::SetLobbyCountdown, "C++: ServerWrapper::SetLobbyCountdown(int) --> void", "newLobbyCountdown"_a);
		cl.def("GetLobbyTime", (float (ServerWrapper::*)()) &ServerWrapper::GetLobbyTime, "C++: ServerWrapper::GetLobbyTime() --> float");
		cl.def("SetLobbyTime", (void (ServerWrapper::*)(float)) &ServerWrapper::SetLobbyTime, "C++: ServerWrapper::SetLobbyTime(float) --> void", "newLobbyTime"_a);
		cl.def("GetLobbySpawnRestartTime", (int (ServerWrapper::*)()) &ServerWrapper::GetLobbySpawnRestartTime, "C++: ServerWrapper::GetLobbySpawnRestartTime() --> int");
		cl.def("SetLobbySpawnRestartTime", (void (ServerWrapper::*)(int)) &ServerWrapper::SetLobbySpawnRestartTime, "C++: ServerWrapper::SetLobbySpawnRestartTime(int) --> void", "newLobbySpawnRestartTime"_a);
		cl.def("GetPauser", (class PlayerControllerWrapper (ServerWrapper::*)()) &ServerWrapper::GetPauser, "C++: ServerWrapper::GetPauser() --> class PlayerControllerWrapper");
		cl.def("SetPauser", (void (ServerWrapper::*)(class PlayerControllerWrapper)) &ServerWrapper::SetPauser, "C++: ServerWrapper::SetPauser(class PlayerControllerWrapper) --> void", "newPauser"_a);
		cl.def("GetPlayerCarCount", (int (ServerWrapper::*)()) &ServerWrapper::GetPlayerCarCount, "C++: ServerWrapper::GetPlayerCarCount() --> int");
		cl.def("ReplicateSkillTiers", (void (ServerWrapper::*)()) &ServerWrapper::ReplicateSkillTiers, "C++: ServerWrapper::ReplicateSkillTiers() --> void");
		cl.def("RemoveTeamSelection", (void (ServerWrapper::*)()) &ServerWrapper::RemoveTeamSelection, "C++: ServerWrapper::RemoveTeamSelection() --> void");
		cl.def("CheckStart", (void (ServerWrapper::*)()) &ServerWrapper::CheckStart, "C++: ServerWrapper::CheckStart() --> void");
		cl.def("StartLobbyTimer", (void (ServerWrapper::*)()) &ServerWrapper::StartLobbyTimer, "C++: ServerWrapper::StartLobbyTimer() --> void");
		cl.def("HandleCountdownTick", (void (ServerWrapper::*)()) &ServerWrapper::HandleCountdownTick, "C++: ServerWrapper::HandleCountdownTick() --> void");
		cl.def("CheckForCountdownAction", (void (ServerWrapper::*)()) &ServerWrapper::CheckForCountdownAction, "C++: ServerWrapper::CheckForCountdownAction() --> void");
		cl.def("LobbyCountdownTick", (void (ServerWrapper::*)()) &ServerWrapper::LobbyCountdownTick, "C++: ServerWrapper::LobbyCountdownTick() --> void");
		cl.def("CanSpawnBots", (bool (ServerWrapper::*)()) &ServerWrapper::CanSpawnBots, "C++: ServerWrapper::CanSpawnBots() --> bool");
		cl.def("StartRound", (void (ServerWrapper::*)()) &ServerWrapper::StartRound, "C++: ServerWrapper::StartRound() --> void");
		cl.def("EndRound", (void (ServerWrapper::*)()) &ServerWrapper::EndRound, "C++: ServerWrapper::EndRound() --> void");
		cl.def("SetBallEventListeners", (void (ServerWrapper::*)(class BallWrapper, unsigned long)) &ServerWrapper::SetBallEventListeners, "C++: ServerWrapper::SetBallEventListeners(class BallWrapper, unsigned long) --> void", "Ball"_a, "bListen"_a);
		cl.def("CanAwardPoints", (bool (ServerWrapper::*)()) &ServerWrapper::CanAwardPoints, "C++: ServerWrapper::CanAwardPoints() --> bool");
		cl.def("HandleCarTouch", (void (ServerWrapper::*)(class BallWrapper, class CarWrapper, unsigned char)) &ServerWrapper::HandleCarTouch, "C++: ServerWrapper::HandleCarTouch(class BallWrapper, class CarWrapper, unsigned char) --> void", "Ball"_a, "HitCar"_a, "HitType"_a);
		cl.def("SetBallHasBeenHit2", (void (ServerWrapper::*)()) &ServerWrapper::SetBallHasBeenHit2, "C++: ServerWrapper::SetBallHasBeenHit2() --> void");
		cl.def("DetermineScoreTouchIndex", (int (ServerWrapper::*)(class BallWrapper, class GoalWrapper)) &ServerWrapper::DetermineScoreTouchIndex, "C++: ServerWrapper::DetermineScoreTouchIndex(class BallWrapper, class GoalWrapper) --> int", "Ball"_a, "Goal"_a);
		cl.def("DetermineAssistTouchIndex", (int (ServerWrapper::*)(class BallWrapper, int)) &ServerWrapper::DetermineAssistTouchIndex, "C++: ServerWrapper::DetermineAssistTouchIndex(class BallWrapper, int) --> int", "Ball"_a, "ScoreIdx"_a);
		cl.def("UpdateTotalGameTimePlayed", (void (ServerWrapper::*)(float)) &ServerWrapper::UpdateTotalGameTimePlayed, "C++: ServerWrapper::UpdateTotalGameTimePlayed(float) --> void", "DeltaTime"_a);
		cl.def("UpdateGameTime", (void (ServerWrapper::*)(float)) &ServerWrapper::UpdateGameTime, "C++: ServerWrapper::UpdateGameTime(float) --> void", "DeltaTime"_a);
		cl.def("CanUpdateGameTime", (bool (ServerWrapper::*)()) &ServerWrapper::CanUpdateGameTime, "C++: ServerWrapper::CanUpdateGameTime() --> bool");
		cl.def("StartReplay", (void (ServerWrapper::*)()) &ServerWrapper::StartReplay, "C++: ServerWrapper::StartReplay() --> void");
		cl.def("HandleReplayFinished", (void (ServerWrapper::*)(class ReplayDirectorWrapper)) &ServerWrapper::HandleReplayFinished, "C++: ServerWrapper::HandleReplayFinished(class ReplayDirectorWrapper) --> void", "InReplay"_a);
		cl.def("GotoPodiumSpotlight", (void (ServerWrapper::*)()) &ServerWrapper::GotoPodiumSpotlight, "C++: ServerWrapper::GotoPodiumSpotlight() --> void");
		cl.def("UpdateSpotlight", (void (ServerWrapper::*)()) &ServerWrapper::UpdateSpotlight, "C++: ServerWrapper::UpdateSpotlight() --> void");
		cl.def("SpawnPodiumCars", (void (ServerWrapper::*)()) &ServerWrapper::SpawnPodiumCars, "C++: ServerWrapper::SpawnPodiumCars() --> void");
		cl.def("CanEnableCarPodiumMovement", (bool (ServerWrapper::*)()) &ServerWrapper::CanEnableCarPodiumMovement, "C++: ServerWrapper::CanEnableCarPodiumMovement() --> bool");
		cl.def("FinishEvent", (void (ServerWrapper::*)()) &ServerWrapper::FinishEvent, "C++: ServerWrapper::FinishEvent() --> void");
		cl.def("__GameEvent_Soccar_TA__UpdateTeamScores", (bool (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::__GameEvent_Soccar_TA__UpdateTeamScores, "C++: ServerWrapper::__GameEvent_Soccar_TA__UpdateTeamScores(class TeamWrapper) --> bool", "T"_a);
		cl.def("__GameEvent_Soccar_TA__SubmitMatchComplete", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::__GameEvent_Soccar_TA__SubmitMatchComplete, "C++: ServerWrapper::__GameEvent_Soccar_TA__SubmitMatchComplete(class PriWrapper) --> void", "PRI"_a);
		cl.def("__GameEvent_Soccar_TA__CheckStart", (void (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::__GameEvent_Soccar_TA__CheckStart, "C++: ServerWrapper::__GameEvent_Soccar_TA__CheckStart(class TeamWrapper) --> void", "T"_a);
		cl.def("__GameEvent_Soccar_TA__EndState", (void (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::__GameEvent_Soccar_TA__EndState, "C++: ServerWrapper::__GameEvent_Soccar_TA__EndState(class TeamWrapper) --> void", "T"_a);
		cl.def("__ReplicatedServerPerformanceState__ChangeNotifyFunc", (void (ServerWrapper::*)()) &ServerWrapper::__ReplicatedServerPerformanceState__ChangeNotifyFunc, "C++: ServerWrapper::__ReplicatedServerPerformanceState__ChangeNotifyFunc() --> void");
		cl.def("__bClubMatch__ChangeNotifyFunc", (void (ServerWrapper::*)()) &ServerWrapper::__bClubMatch__ChangeNotifyFunc, "C++: ServerWrapper::__bClubMatch__ChangeNotifyFunc() --> void");
		cl.def("__bShowIntroScene__ChangeNotifyFunc", (void (ServerWrapper::*)()) &ServerWrapper::__bShowIntroScene__ChangeNotifyFunc, "C++: ServerWrapper::__bShowIntroScene__ChangeNotifyFunc() --> void");
		cl.def("__WaitTimeRemaining__ChangeNotifyFunc", (void (ServerWrapper::*)()) &ServerWrapper::__WaitTimeRemaining__ChangeNotifyFunc, "C++: ServerWrapper::__WaitTimeRemaining__ChangeNotifyFunc() --> void");
		cl.def("CheckJoinInProgress", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::CheckJoinInProgress, "C++: ServerWrapper::CheckJoinInProgress(class PriWrapper) --> void", "PRI"_a);
		cl.def("AllowDynamicCrowd", (bool (ServerWrapper::*)()) &ServerWrapper::AllowDynamicCrowd, "C++: ServerWrapper::AllowDynamicCrowd() --> bool");
		cl.def("AddBallTrajectory", (void (ServerWrapper::*)(class BallWrapper)) &ServerWrapper::AddBallTrajectory, "C++: ServerWrapper::AddBallTrajectory(class BallWrapper) --> void", "InBall"_a);
		cl.def("ShowScorerGoalMessage", (bool (ServerWrapper::*)()) &ServerWrapper::ShowScorerGoalMessage, "C++: ServerWrapper::ShowScorerGoalMessage() --> bool");
		cl.def("CanUseBallCam", (bool (ServerWrapper::*)()) &ServerWrapper::CanUseBallCam, "C++: ServerWrapper::CanUseBallCam() --> bool");
		cl.def("DisableStatXP", (bool (ServerWrapper::*)()) &ServerWrapper::DisableStatXP, "C++: ServerWrapper::DisableStatXP() --> bool");
		cl.def("SetDisableGoalDelay", (void (ServerWrapper::*)(unsigned long)) &ServerWrapper::SetDisableGoalDelay, "C++: ServerWrapper::SetDisableGoalDelay(unsigned long) --> void", "bInDisableGoalDelay"_a);
		cl.def("ForceMatchStart", (void (ServerWrapper::*)()) &ServerWrapper::ForceMatchStart, "C++: ServerWrapper::ForceMatchStart() --> void");
		cl.def("RemoveLocalPlayer", (void (ServerWrapper::*)(class PlayerControllerWrapper)) &ServerWrapper::RemoveLocalPlayer, "C++: ServerWrapper::RemoveLocalPlayer(class PlayerControllerWrapper) --> void", "Player"_a);
		cl.def("AddLocalPlayer", (void (ServerWrapper::*)(class PlayerControllerWrapper)) &ServerWrapper::AddLocalPlayer, "C++: ServerWrapper::AddLocalPlayer(class PlayerControllerWrapper) --> void", "Player"_a);
		cl.def("DestroyGoalIndicators", (void (ServerWrapper::*)(class PlayerControllerWrapper)) &ServerWrapper::DestroyGoalIndicators, "C++: ServerWrapper::DestroyGoalIndicators(class PlayerControllerWrapper) --> void", "Player"_a);
		cl.def("CreateGoalIndicators", (void (ServerWrapper::*)(class PlayerControllerWrapper)) &ServerWrapper::CreateGoalIndicators, "C++: ServerWrapper::CreateGoalIndicators(class PlayerControllerWrapper) --> void", "Player"_a);
		cl.def("BeginHighlightsReplay", (void (ServerWrapper::*)()) &ServerWrapper::BeginHighlightsReplay, "C++: ServerWrapper::BeginHighlightsReplay() --> void");
		cl.def("ShouldCountUp", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldCountUp, "C++: ServerWrapper::ShouldCountUp() --> bool");
		cl.def("ShouldAllowVoteToForfeit", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldAllowVoteToForfeit, "C++: ServerWrapper::ShouldAllowVoteToForfeit() --> bool");
		cl.def("ShouldHaveLeaveMatchPenalty", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldHaveLeaveMatchPenalty, "C++: ServerWrapper::ShouldHaveLeaveMatchPenalty() --> bool");
		cl.def("SetPaused", (void (ServerWrapper::*)(class PlayerControllerWrapper, unsigned long)) &ServerWrapper::SetPaused, "C++: ServerWrapper::SetPaused(class PlayerControllerWrapper, unsigned long) --> void", "InPauser"_a, "bInPaused"_a);
		cl.def("ShouldCountdownResumeFromPause", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldCountdownResumeFromPause, "C++: ServerWrapper::ShouldCountdownResumeFromPause() --> bool");
		cl.def("SetScoreAndTime", (void (ServerWrapper::*)(class PlayerControllerWrapper, int, int, int, unsigned long, unsigned long)) &ServerWrapper::SetScoreAndTime, "C++: ServerWrapper::SetScoreAndTime(class PlayerControllerWrapper, int, int, int, unsigned long, unsigned long) --> void", "PC"_a, "NewScoreTeam0"_a, "NewScoreTeam1"_a, "InGameTimeRemaining"_a, "bInOvertime"_a, "bRestartRound"_a);
		cl.def("SaveLocalPlayerStats", (void (ServerWrapper::*)()) &ServerWrapper::SaveLocalPlayerStats, "C++: ServerWrapper::SaveLocalPlayerStats() --> void");
		cl.def("ShouldPlayReplay", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldPlayReplay, "C++: ServerWrapper::ShouldPlayReplay() --> bool");
		cl.def("ShouldRecordReplay", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldRecordReplay, "C++: ServerWrapper::ShouldRecordReplay() --> bool");
		cl.def("OnBallHasBeenHit", (void (ServerWrapper::*)()) &ServerWrapper::OnBallHasBeenHit, "C++: ServerWrapper::OnBallHasBeenHit() --> void");
		cl.def("SpawnBall2", (class BallWrapper (ServerWrapper::*)(struct Vector &, unsigned long, unsigned long, std::string)) &ServerWrapper::SpawnBall2, "C++: ServerWrapper::SpawnBall2(struct Vector &, unsigned long, unsigned long, std::string) --> class BallWrapper", "SpawnLoc"_a, "bWake"_a, "bSpawnCannon"_a, "BallArch"_a);
		cl.def("GetTotalScore", (int (ServerWrapper::*)()) &ServerWrapper::GetTotalScore, "C++: ServerWrapper::GetTotalScore() --> int");
		cl.def("HandleCarSet", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::HandleCarSet, "C++: ServerWrapper::HandleCarSet(class PriWrapper) --> void", "InPRI"_a);
		cl.def("RemovePRI", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::RemovePRI, "C++: ServerWrapper::RemovePRI(class PriWrapper) --> void", "PRI"_a);
		cl.def("AddPRI", (void (ServerWrapper::*)(class PriWrapper)) &ServerWrapper::AddPRI, "C++: ServerWrapper::AddPRI(class PriWrapper) --> void", "PRI"_a);
		cl.def("OnMatchWinnerSet", (void (ServerWrapper::*)()) &ServerWrapper::OnMatchWinnerSet, "C++: ServerWrapper::OnMatchWinnerSet() --> void");
		cl.def("OnGameWinnerSet", (void (ServerWrapper::*)()) &ServerWrapper::OnGameWinnerSet, "C++: ServerWrapper::OnGameWinnerSet() --> void");
		cl.def("MVPSort", (int (ServerWrapper::*)(class PriWrapper, class PriWrapper)) &ServerWrapper::MVPSort, "C++: ServerWrapper::MVPSort(class PriWrapper, class PriWrapper) --> int", "A"_a, "B"_a);
		cl.def("HandleHitGoal", (void (ServerWrapper::*)(class BallWrapper, class GoalWrapper)) &ServerWrapper::HandleHitGoal, "C++: ServerWrapper::HandleHitGoal(class BallWrapper, class GoalWrapper) --> void", "Ball"_a, "Goal"_a);
		cl.def("ClearReplicatedScoredOnTeam", (void (ServerWrapper::*)()) &ServerWrapper::ClearReplicatedScoredOnTeam, "C++: ServerWrapper::ClearReplicatedScoredOnTeam() --> void");
		cl.def("TriggerScoreChangedEvent", (void (ServerWrapper::*)()) &ServerWrapper::TriggerScoreChangedEvent, "C++: ServerWrapper::TriggerScoreChangedEvent() --> void");
		cl.def("HandleScoreUpdated", (void (ServerWrapper::*)(class TeamWrapper)) &ServerWrapper::HandleScoreUpdated, "C++: ServerWrapper::HandleScoreUpdated(class TeamWrapper) --> void", "Team"_a);
		cl.def("OnAllTeamsCreated", (void (ServerWrapper::*)()) &ServerWrapper::OnAllTeamsCreated, "C++: ServerWrapper::OnAllTeamsCreated() --> void");
		cl.def("TriggerGoalScoreEvent", (void (ServerWrapper::*)(int, class CarWrapper)) &ServerWrapper::TriggerGoalScoreEvent, "C++: ServerWrapper::TriggerGoalScoreEvent(int, class CarWrapper) --> void", "TeamScoredOn"_a, "Scorer"_a);
		cl.def("SetTotalGameBalls2", (void (ServerWrapper::*)(int)) &ServerWrapper::SetTotalGameBalls2, "C++: ServerWrapper::SetTotalGameBalls2(int) --> void", "TotalBalls"_a);
		cl.def("RecordRecentPlayers", (void (ServerWrapper::*)()) &ServerWrapper::RecordRecentPlayers, "C++: ServerWrapper::RecordRecentPlayers() --> void");
		cl.def("UpdateStats", (void (ServerWrapper::*)()) &ServerWrapper::UpdateStats, "C++: ServerWrapper::UpdateStats() --> void");
		cl.def("NotifyKismetOfCurrentTime", (void (ServerWrapper::*)()) &ServerWrapper::NotifyKismetOfCurrentTime, "C++: ServerWrapper::NotifyKismetOfCurrentTime() --> void");
		cl.def("EnoughTimePassedToForfeit", (bool (ServerWrapper::*)()) &ServerWrapper::EnoughTimePassedToForfeit, "C++: ServerWrapper::EnoughTimePassedToForfeit() --> bool");
		cl.def("OnGameTimeUpdated", (void (ServerWrapper::*)()) &ServerWrapper::OnGameTimeUpdated, "C++: ServerWrapper::OnGameTimeUpdated() --> void");
		cl.def("OnOvertimeUpdated", (void (ServerWrapper::*)()) &ServerWrapper::OnOvertimeUpdated, "C++: ServerWrapper::OnOvertimeUpdated() --> void");
		cl.def("ForceOvertime", (void (ServerWrapper::*)()) &ServerWrapper::ForceOvertime, "C++: ServerWrapper::ForceOvertime() --> void");
		cl.def("StartOvertime", (void (ServerWrapper::*)()) &ServerWrapper::StartOvertime, "C++: ServerWrapper::StartOvertime() --> void");
		cl.def("OnMyHalf", (bool (ServerWrapper::*)(struct Vector &, unsigned char)) &ServerWrapper::OnMyHalf, "C++: ServerWrapper::OnMyHalf(struct Vector &, unsigned char) --> bool", "TestLocation"_a, "TeamNum"_a);
		cl.def("GetWinningTeam", (class TeamWrapper (ServerWrapper::*)()) &ServerWrapper::GetWinningTeam, "C++: ServerWrapper::GetWinningTeam() --> class TeamWrapper");
		cl.def("ResetPickups", (void (ServerWrapper::*)()) &ServerWrapper::ResetPickups, "C++: ServerWrapper::ResetPickups() --> void");
		cl.def("ResetPlayers", (void (ServerWrapper::*)()) &ServerWrapper::ResetPlayers, "C++: ServerWrapper::ResetPlayers() --> void");
		cl.def("OnBallSpawned", (void (ServerWrapper::*)(class BallWrapper)) &ServerWrapper::OnBallSpawned, "C++: ServerWrapper::OnBallSpawned(class BallWrapper) --> void", "NewBall"_a);
		cl.def("ResetBalls", (void (ServerWrapper::*)()) &ServerWrapper::ResetBalls, "C++: ServerWrapper::ResetBalls() --> void");
		cl.def("DestroyCars", (void (ServerWrapper::*)()) &ServerWrapper::DestroyCars, "C++: ServerWrapper::DestroyCars() --> void");
		cl.def("FreezePawns", (void (ServerWrapper::*)()) &ServerWrapper::FreezePawns, "C++: ServerWrapper::FreezePawns() --> void");
		cl.def("DestroyBalls", (void (ServerWrapper::*)()) &ServerWrapper::DestroyBalls, "C++: ServerWrapper::DestroyBalls() --> void");
		cl.def("RemoveGameBall", (void (ServerWrapper::*)(class BallWrapper)) &ServerWrapper::RemoveGameBall, "C++: ServerWrapper::RemoveGameBall(class BallWrapper) --> void", "Ball"_a);
		cl.def("AddGameBall", (void (ServerWrapper::*)(class BallWrapper)) &ServerWrapper::AddGameBall, "C++: ServerWrapper::AddGameBall(class BallWrapper) --> void", "Ball"_a);
		cl.def("StartNewRound", (void (ServerWrapper::*)()) &ServerWrapper::StartNewRound, "C++: ServerWrapper::StartNewRound() --> void");
		cl.def("CheckForAutoBalance", (void (ServerWrapper::*)()) &ServerWrapper::CheckForAutoBalance, "C++: ServerWrapper::CheckForAutoBalance() --> void");
		cl.def("HasWinner", (bool (ServerWrapper::*)()) &ServerWrapper::HasWinner, "C++: ServerWrapper::HasWinner() --> bool");
		cl.def("SubmitMatch2", (void (ServerWrapper::*)()) &ServerWrapper::SubmitMatch2, "C++: ServerWrapper::SubmitMatch2() --> void");
		cl.def("SubmitMatchComplete2", (void (ServerWrapper::*)()) &ServerWrapper::SubmitMatchComplete2, "C++: ServerWrapper::SubmitMatchComplete2() --> void");
		cl.def("OnMatchEnded", (void (ServerWrapper::*)()) &ServerWrapper::OnMatchEnded, "C++: ServerWrapper::OnMatchEnded() --> void");
		cl.def("ShouldDoPodiumSpotlight", (bool (ServerWrapper::*)()) &ServerWrapper::ShouldDoPodiumSpotlight, "C++: ServerWrapper::ShouldDoPodiumSpotlight() --> bool");
		cl.def("EndGame", (void (ServerWrapper::*)()) &ServerWrapper::EndGame, "C++: ServerWrapper::EndGame() --> void");
		cl.def("UpdateTeamScores2", (void (ServerWrapper::*)()) &ServerWrapper::UpdateTeamScores2, "C++: ServerWrapper::UpdateTeamScores2() --> void");
		cl.def("StartNewGame", (void (ServerWrapper::*)()) &ServerWrapper::StartNewGame, "C++: ServerWrapper::StartNewGame() --> void");
		cl.def("ResetGame", (void (ServerWrapper::*)()) &ServerWrapper::ResetGame, "C++: ServerWrapper::ResetGame() --> void");
		cl.def("ClearReplicatedStatEvent", (void (ServerWrapper::*)()) &ServerWrapper::ClearReplicatedStatEvent, "C++: ServerWrapper::ClearReplicatedStatEvent() --> void");
		cl.def("eventDestroyed", (void (ServerWrapper::*)()) &ServerWrapper::eventDestroyed, "C++: ServerWrapper::eventDestroyed() --> void");
		cl.def("InitBotDetection", (void (ServerWrapper::*)()) &ServerWrapper::InitBotDetection, "C++: ServerWrapper::InitBotDetection() --> void");
		cl.def("InitCrowdManager", (void (ServerWrapper::*)()) &ServerWrapper::InitCrowdManager, "C++: ServerWrapper::InitCrowdManager() --> void");
		cl.def("InitField", (void (ServerWrapper::*)()) &ServerWrapper::InitField, "C++: ServerWrapper::InitField() --> void");
		cl.def("InitGameObserver", (void (ServerWrapper::*)()) &ServerWrapper::InitGameObserver, "C++: ServerWrapper::InitGameObserver() --> void");
		cl.def("OnInit", (void (ServerWrapper::*)()) &ServerWrapper::OnInit, "C++: ServerWrapper::OnInit() --> void");
		cl.def("InitMutators", (void (ServerWrapper::*)()) &ServerWrapper::InitMutators, "C++: ServerWrapper::InitMutators() --> void");
		cl.def("OnClubMatch", (void (ServerWrapper::*)()) &ServerWrapper::OnClubMatch, "C++: ServerWrapper::OnClubMatch() --> void");
		cl.def("CanInitClubMatch", (bool (ServerWrapper::*)()) &ServerWrapper::CanInitClubMatch, "C++: ServerWrapper::CanInitClubMatch() --> bool");
		cl.def("AssignCustomTeamSettings", (void (ServerWrapper::*)()) &ServerWrapper::AssignCustomTeamSettings, "C++: ServerWrapper::AssignCustomTeamSettings() --> void");
		cl.def("InitGame2", (void (ServerWrapper::*)(std::string)) &ServerWrapper::InitGame2, "C++: ServerWrapper::InitGame2(std::string) --> void", "Options"_a);
		cl.def("EventGameWinnerSet", (void (ServerWrapper::*)(class ServerWrapper)) &ServerWrapper::EventGameWinnerSet, "C++: ServerWrapper::EventGameWinnerSet(class ServerWrapper) --> void", "GameEvent"_a);
		cl.def("EventGoalScored", (void (ServerWrapper::*)(class ServerWrapper, class BallWrapper, class GoalWrapper, int, int)) &ServerWrapper::EventGoalScored, "C++: ServerWrapper::EventGoalScored(class ServerWrapper, class BallWrapper, class GoalWrapper, int, int) --> void", "GameEvent"_a, "Ball"_a, "Goal"_a, "ScoreIndex"_a, "AssistIdx"_a);
	}
}
