from typing import Callable

class Vector:
    x: float = ...
    y: float = ...
    z: float = ...

    def __init__(self, x: float, y: float, z: float): ...
    def magnitude(self) -> float: ...
    def normalize(self) -> None: ...

class ActorWrapper:

    def GetLocation(self) -> Vector: ...
    def SetLocation(self, location: Vector) -> None: ...
    def GetVelocity(self) -> Vector: ...
    def SetVelocity(self, velocity: Vector) -> None: ...
    def AddVelocity(self, velocity: Vector) -> None: ...
    def Stop(self) -> None: ...
    def GetAngularVelocity(self) -> Vector: ...
    def SetAngularVelocity(self, angularVelocity: Vector, addToCurrent: bool) -> None: ...
    def IsNull(self) -> bool: ...


class RBActorWrapper(ActorWrapper):
    def GetMaxLinearSpeed(self) -> float: ...
    def SetMaxLinearSpeed(self, newMaxLinearSpeed: float) -> None: ...
    def GetMaxAngularSpeed(self) -> float: ...
    def SetMaxAngularSpeed(self, newMaxAngularSpeed: float) -> None: ...
    def SetMass(self, newMass: float) -> None: ...
    def AddTorque(self, torque: Vector, forceMode: int) -> None: ...
    def AddForce(self, force: Vector, forceMode: int) -> None: ...


class VehicleWrapper(RBActorWrapper):
    def IsOnWall(self) -> bool: ...
    def IsOnGround(self) -> bool: ...

class CarWrapper(VehicleWrapper):
    def IsBoostCheap(self) -> bool: ...
    def SetBoostCheap(self, b: bool) -> None: ...
    def ForceBoost(self, force: bool) -> None: ...
    def GetOwnerName(self) -> str: ...
    def Destroy(self) -> None: ...
    def Demolish(self) -> None: ...
    def RespawnInPlace(self) -> None: ...
    def SetCarScale(self, scale: float) -> None: ...

class BallWrapper(RBActorWrapper):
    def GetLastTouchTime(self) -> float: ...
    def GetMagnusCoefficient(self) -> Vector: ...
    def SetMagnusCoefficient(self, newMagnusCoefficient: Vector): ...
    def GetRadius(self) -> float: ...
    def SetRadius(self, newRadius: float): ...
    def DoDestroy(self) -> None: ...
    def DoExplode(self) -> None: ...
    def Launch(self, launchPosition: Vector, launchDirection: Vector) -> None: ...
    def SetWorldBounceScale(self, newScale: float) -> None: ...
    def SetCarBounceScale(self, newScale: float) -> None: ...
    def SetBallMaxLinearSpeedScale(self, newScale: float) -> None: ...
    def SetBallGravityScale(self, newScale: float) -> None: ...
    def SetBallScale(self, newScale: float) -> None: ...


class ServerWrapper:
    def GetSecondsElapsed(self) -> float: ...
    def GetBall(self) -> BallWrapper: ...
    def GetGameCar(self) -> CarWrapper: ...


class GameWrapper:
    def HookEvent(self, eventName: str, callback: Callable[[str], None]) -> None: ...
    def HookEventPost(self, eventName: str, callback: Callable[[str], None]) -> None: ...
    def UnhookEvent(self, eventName: str) -> None: ...
    def IsInGame(self) -> bool: ...
    def IsInOnlineGame(self) -> bool: ...
    def IsInFreeplay(self) -> bool: ...
    def IsInReplay(self) -> bool: ...
    def IsInCustomTraining(self) -> bool: ...
    def IsSpectatingInOnlineGame(self) -> bool: ...
    def GetGameEventAsServer(self) -> ServerWrapper: ...
